const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os'),{spawnSync}=require('child_process'),vm=require('vm');
const M=require('../public/app/studio-model'),{renderStudio,probe}=require('../lib/studio-render');
const base=()=>M.validate({version:1,segments:[{start:0,end:3,speed:1}],words:[{word:'Hello',start:0,end:.5},{word:'world',start:2,end:2.5}],layers:[]},3);
test('split and reorder preserve source timings and map captions to edited time',()=>{let p=M.split(base(),1);assert.equal(p.segments.length,2);p.segments.reverse();p.segments[0].speed=2;assert.equal(M.duration(p),2);const w=M.words(p,p.words);assert.deepEqual(w,[{word:'world',start:.5,end:.75},{word:'Hello',start:1,end:1.5}]);assert.equal(M.locate(p,1.2).source,.19999999999999996);});
test('invalid ranges, filter injection, foreign assets and zero-length words are rejected',()=>{for(const patch of [{segments:[{start:3,end:1,speed:1}]},{segments:[{start:0,end:3,speed:NaN}]},{layers:[{type:'image',assetId:'foreign',start:0,end:1}]},{captionColor:'white;movie=http://evil'},{words:[{word:'bad',start:2,end:1}]}])assert.throws(()=>M.validate({...base(),...patch},3));});
test('automatic pause removal yields editable segments without mutating original',()=>{const p=base(),q=M.removePauses(p);assert.equal(q.segments.length,2);assert.ok(M.duration(q)<M.duration(p));assert.equal(p.segments.length,1);});
test('real renderer exports cut/speed changes, text, image and music, preserving source',async()=>{
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'studio-test-'));try{const source=path.join(dir,'source.mp4'),image=path.join(dir,'logo.png'),audio=path.join(dir,'music.wav');
const ff=(args)=>{const r=spawnSync('ffmpeg',['-hide_banner','-loglevel','error',...args],{timeout:30000});assert.equal(r.status,0,String(r.stderr));};
ff(['-f','lavfi','-i','color=blue:s=320x240:d=3:r=30','-f','lavfi','-i','sine=frequency=440:duration=3','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac','-shortest','-y',source]);
ff(['-f','lavfi','-i','color=red:s=100x100','-frames:v','1','-y',image]);ff(['-f','lavfi','-i','sine=frequency=880:duration=3','-y',audio]);const original=fs.readFileSync(source);
const assets=[{id:'logo',type:'image',local:image},{id:'sound',type:'audio',local:audio}];let p=base();p.segments=[{start:1,end:3,speed:2},{start:0,end:.5,speed:.5}];p.layers=[{type:'text',text:'My title {\\pos(0,0)}',start:0,end:1,size:100,color:'#ffffff',x:.5,y:.2},{type:'image',assetId:'logo',start:0,end:2,width:.25,x:.5,y:.5}];p.audio={assetId:'sound',volume:.2,offset:0};p.fade=.2;p=M.validate(p,3,assets);
const out=await renderStudio(source,p,assets,dir,'free');const info=await probe(out);assert.ok(Math.abs(Number(info.format.duration)-2)<.15);const v=info.streams.find(s=>s.codec_type==='video');assert.equal(v.width,720);assert.equal(v.height,1280);assert.ok(info.streams.some(s=>s.codec_type==='audio'));assert.deepEqual(original,fs.readFileSync(source));assert.ok(!fs.readFileSync(path.join(dir,'studio.ass'),'utf8').includes('\\pos(0,0)'));
const pix=spawnSync('ffmpeg',['-v','error','-ss','0.5','-i',out,'-vf','crop=2:2:359:639','-frames:v','1','-f','rawvideo','-pix_fmt','rgb24','pipe:1']);assert.equal(pix.status,0,String(pix.stderr));assert.ok(pix.stdout[0]>150&&pix.stdout[2]<80,'image layer rendered red over blue source');
}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('silent sources still export a playable audio/video timeline',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'studio-silent-'));try{const source=path.join(dir,'silent.mp4');const r=spawnSync('ffmpeg',['-v','error','-f','lavfi','-i','color=green:s=160x160:d=0.5','-c:v','libx264','-y',source]);assert.equal(r.status,0,String(r.stderr));const p=M.validate({version:1,segments:[{start:0,end:.5,speed:1}],captions:false,layers:[]},.5);const out=await renderStudio(source,p,[],dir,'single');assert.ok((await probe(out)).streams.some(s=>s.codec_type==='audio'));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('imported footage and rotation render through the same timeline',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'studio-import-'));try{const source=path.join(dir,'a.mp4'),insert=path.join(dir,'b.mp4');for(const [file,color]of [[source,'blue'],[insert,'red']]){const r=spawnSync('ffmpeg',['-v','error','-f','lavfi','-i','color='+color+':s=160x100:d=1','-c:v','libx264','-y',file]);assert.equal(r.status,0,String(r.stderr));}const assets=[{id:'insert',type:'video',duration:1,local:insert}];const p=M.validate({version:1,segments:[{start:0,end:.5,speed:1},{assetId:'insert',start:0,end:.5,speed:1}],rotation:90,ratio:'1:1',captions:false,layers:[]},1,assets);const out=await renderStudio(source,p,assets,dir,'single');assert.ok(Math.abs(Number((await probe(out)).format.duration)-1)<.15);const pix=spawnSync('ffmpeg',['-v','error','-ss','0.8','-i',out,'-vf','crop=2:2:100:100','-frames:v','1','-f','rawvideo','-pix_fmt','rgb24','pipe:1']);assert.equal(pix.status,0,String(pix.stderr));assert.ok(pix.stdout[0]>150&&pix.stdout[2]<80);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('studio API enforces ownership and keeps drafts independent of original clip',async()=>{
const express=require('express'),rows={own:{id:'own',user_id:'alice',storage_path:'original.mp4',master_path:'master.mp4',in_start:0,in_end:3,edit:{captionStyle:'classic'},words:[{word:'early',start:-.2,end:.2},{word:'last',start:2.9,end:3.4},{word:'outside',start:3.5,end:4}]},other:{id:'other',user_id:'bob',storage_path:'secret.mp4',in_end:3,master_path:'secret-master.mp4',edit:{}}};
const admin={from(){let filters={},patch;const q={select(){return q},eq(k,v){filters[k]=v;return q},update(x){patch=x;return q},async maybeSingle(){return q.single()},async single(){const row=rows[filters.id];return {data:row&&row.user_id===filters.user_id?JSON.parse(JSON.stringify(row)):null,error:null}},then(resolve){const row=rows[filters.id];if(row&&row.user_id===filters.user_id&&patch)Object.assign(row,patch);return Promise.resolve({error:null}).then(resolve)}};return q},storage:{from(){return {createSignedUrl:async p=>({data:{signedUrl:'https://example.test/'+p}})}}}};
const requireUser=(req,res,next)=>{if(req.headers.authorization!=='Bearer alice')return res.status(401).json({error:'Sign in required'});req.user={id:'alice'};next();};
const mod={exports:{}};const realRequire=require;const file=path.join(__dirname,'../routes/studio.js');vm.runInNewContext(fs.readFileSync(file,'utf8'),{module:mod,process,console,setTimeout,setImmediate,Buffer,require:p=>p==='../lib/supabase'?{admin}:p==='../lib/requireUser'?{requireUser}:p==='../public/app/studio-model'?M:p==='../lib/studio-render'?{renderStudio,probe}:p==='../lib/captionStyles'?realRequire('../lib/captionStyles'):p==='../lib/pipeline'?{activeJobs:()=>0}:realRequire(p)});
const app=express();app.use(express.json());app.use('/api',mod.exports);const server=app.listen(0);await new Promise(r=>server.once('listening',r));const origin='http://127.0.0.1:'+server.address().port;
try{let r=await fetch(origin+'/api/studio/own');assert.equal(r.status,401);r=await fetch(origin+'/api/studio/other',{headers:{Authorization:'Bearer alice'}});assert.equal(r.status,404);r=await fetch(origin+'/api/studio/own',{headers:{Authorization:'Bearer alice'}});assert.equal(r.status,200);const opened=await r.json();assert.equal(opened.clip.url,'https://example.test/master.mp4');assert.equal(opened.clip.words.length,2);assert.equal(opened.clip.words[0].start,0);assert.equal(opened.clip.words[1].end,3);r=await fetch(origin+'/api/studio/own/draft',{method:'PUT',headers:{Authorization:'Bearer alice','Content-Type':'application/json'},body:JSON.stringify(base())});assert.equal(r.status,200);assert.ok(rows.own.edit.studioDraft);assert.equal(rows.own.storage_path,'original.mp4');assert.equal(rows.own.edit.captionStyle,'classic');r=await fetch(origin+'/api/studio/other/draft',{method:'PUT',headers:{Authorization:'Bearer alice','Content-Type':'application/json'},body:JSON.stringify(base())});assert.equal(r.status,404);assert.equal(rows.other.edit.studioDraft,undefined);
}finally{await new Promise(r=>server.close(r));}});
